service/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

urlpatterns = [
    path('maintenances/', MaintenanceListView.as_view(), name='maintenance_list'),
    path('complaints/', ComplaintListView.as_view(), name='complaint_list'),
    path('car/<pk>/maintenances', MaintenanceCarListView.as_view(), name='car_maintenance'),
    path('car/<pk>/complaints', ComplaintCarListView.as_view(), name='car_complaint'),
    path('maintenance/create', MaintenanceCreateView.as_view(), name='maintenance_create'),
    path('complaint/create', ComplaintCreateView.as_view(), name='complaint_create'),
    path('maintenance/<pk>/update', MaintenanceUpdateView.as_view(), name='maintenance_update'),
    path('complaint/<pk>/update', ComplaintUpdateView.as_view(), name='complaint_update'),
    path('maintenance/<pk>/delete', MaintenanceDeleteView.as_view(), name='maintenance_delete'),
    path('complaint/<pk>/delete', ComplaintDeleteView.as_view(), name='complaint_delete'),
    path('maintenance/<pk>/description/<atribute>', MaintenanceDescriptionView.as_view(), name='maintenance_description'),
    path('complaint/<pk>/description/<atribute>', ComplaintDescriptionView.as_view(), name='complaint_description'),

    path('api/maintenances/',MaintenanceListAPI.as_view(),name='maintenance_list_api'),
    path('api/<user>/maintenances/',MaintenanceUserListAPI.as_view(),name='user_maintenance_list_api'),
    path('api/maintenance/<pk>/',MaintenanceDetailAPI.as_view(),name='maintenance_detail_api'),
    path('api/complaints/',ComplaintListAPI.as_view(),name='complaint_list_api'),
    path('api/<user>/complaints/',ComplaintUserListAPI.as_view(),name='user_complaint_list_api'),
    path('api/complaint/<pk>/',ComplaintDetailAPI.as_view(),name='complaint_detail_api'),
]

silant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('service.urls')),
    path('', include('vehicles.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

service/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
from vehicles.models import Car, UserProfile

class TypeMaintenance(models.Model):
    name = models.CharField(max_length=50, verbose_name='Название')
    description = models.TextField(verbose_name='Описание', blank=True, null=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Вид технического обслуживания'
        verbose_name_plural = 'Виды технических обслуживаний'

class Failure(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название')
    description = models.TextField(verbose_name='Описание', blank=True, null=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Характер отказа'
        verbose_name_plural = 'Характеры отказа'

class RecoveryMethod(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название')
    description = models.TextField(verbose_name='Описание', blank=True, null=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Способ восстановления'
        verbose_name_plural = 'Способы восстановления'

class ServiceCompany(models.Model):
    name = models.CharField(max_length=200, verbose_name='Название')
    description = models.TextField(verbose_name='Описание', blank=True, null=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Сервисная компания'
        verbose_name_plural = 'Сервисные компании'

class Maintenance(models.Model):
    type = models.ForeignKey(TypeMaintenance, on_delete=models.CASCADE, verbose_name='Вид ТО')
    date = models.DateField(default=datetime.now, verbose_name='Дата проведения ТО')
    operating_time = models.PositiveIntegerField(default=0, verbose_name='Наработка, м/час')
    order_number = models.CharField(max_length=20, verbose_name='№ заказ-наряда')
    order_date = models.DateField(default=datetime.now, verbose_name='Дата заказ-наряда')
    service_company = models.ForeignKey(ServiceCompany, on_delete=models.CASCADE, verbose_name='Организация, проводившая ТО', null=True, blank=True)
    car = models.ForeignKey(Car, on_delete=models.CASCADE, verbose_name='Машина')

    def __str__(self):
        return f'{self.date} {self.car}'

    class Meta:
        verbose_name = 'Техническое обслуживание'
        verbose_name_plural = 'Технические обслуживания'

class Complaint(models.Model):
    date_failure = models.DateField(default=datetime.now, verbose_name='Дата отказа')
    operating_time = models.PositiveIntegerField(default=0, verbose_name='Наработка, м/час')
    node_failure = models.ForeignKey(Failure, on_delete=models.CASCADE, verbose_name='Узел отказа')
    description_failure = models.TextField(blank=True, null=True, verbose_name='Описание отказа')
    method_recovery = models.ForeignKey(RecoveryMethod, on_delete=models.CASCADE, verbose_name='Способ восстановления')
    repair_parts = models.TextField(blank=True, null=True, verbose_name='Используемые запасные части')
    date_recovery = models.DateField(default=datetime.now, verbose_name='Дата восстановления')
    car = models.ForeignKey(Car, on_delete=models.CASCADE, verbose_name='Машина')
    service_company = models.ForeignKey(ServiceCompany, on_delete=models.CASCADE, verbose_name='Сервисная компания', null=True, blank=True)

    def __str__(self):
        return f'{self.date_failure} {self.car}'

    def downtime(self):
        deltatime = self.date_recovery - self.date_failure
        return deltatime.days

    class Meta:
        verbose_name = 'Рекламация'
        verbose_name_plural = 'Рекламации'

vehicles/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User 

class UserProfile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    is_service = models.BooleanField(default=False, blank=True, verbose_name='Является сотрудником сервисной компании')
    service_company = models.ForeignKey(to='service.ServiceCompany',blank=True, null=True, on_delete=models.PROTECT, verbose_name='Сервисная компания')

    def __str__(self):
        return f'{self.user.username} {self.is_service}'
    
    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'


class Technic(models.Model):
    name = models.CharField(max_length=20, verbose_name='Название')
    description = models.TextField(verbose_name='Описание', blank=True, null=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Модель техники'
        verbose_name_plural = 'Модели техники'

class Engine(models.Model):
    name = models.CharField(max_length=30, verbose_name='Название')
    description = models.TextField(verbose_name='Описание', blank=True, null=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Модель двигателя'
        verbose_name_plural = 'Модели двигателей'

class Transmission(models.Model):
    name = models.CharField(max_length=20, verbose_name='Название')
    description = models.TextField(verbose_name='Описание', blank=True, null=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Модель трансмиссии'
        verbose_name_plural = 'Модели трансмиссий'

class DrivingBridge(models.Model):
    name = models.CharField(max_length=20, verbose_name='Название')
    description = models.TextField(verbose_name='Описание', blank=True, null=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Модель ведущего моста'
        verbose_name_plural = 'Модели ведущих мостов'

class ControlledBridge(models.Model):
    name = models.CharField(max_length=20, verbose_name='Название')
    description = models.TextField(verbose_name='Описание', blank=True, null=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Модель управляемого моста'
        verbose_name_plural = 'Модели управляемых мостов'

class Car(models.Model):
    car_number = models.CharField(unique=True, max_length=12, verbose_name='Зав. № машины')
    technic = models.ForeignKey(Technic, on_delete=models.CASCADE, verbose_name='Модель техники')
    engine = models.ForeignKey(Engine, on_delete=models.CASCADE, verbose_name='Модель двигателя')
    engine_number = models.CharField(max_length=12, verbose_name='Зав. № двигателя')
    transmission = models.ForeignKey(Transmission, on_delete=models.CASCADE, verbose_name='Модель трансмиссии')
    transmission_number = models.CharField(max_length=12, verbose_name='Зав. № трансмиссии')
    driving_bridge = models.ForeignKey(DrivingBridge, on_delete=models.CASCADE, verbose_name='Модель ведущего моста')
    driving_bridge_number = models.CharField(max_length=12, verbose_name='Зав. № ведущего моста')
    controlled_bridge = models.ForeignKey(ControlledBridge, on_delete=models.CASCADE, verbose_name='Модель управляемого моста')
    controlled_bridge_number = models.CharField(max_length=12, verbose_name='Зав. № управляемого моста')
    delivery_contract = models.CharField(max_length=20, verbose_name='Договор поставки №, дата')
    date_shipment = models.DateField(default=datetime.now, verbose_name='Дата отгрузки с завода')
    consignee = models.CharField(max_length=200, verbose_name='Грузополучатель (конечный потребитель)')
    delivery_address = models.CharField(max_length=200, verbose_name='Адрес поставки (эксплуатации)')
    equipment = models.TextField(blank=False,verbose_name='Комплектация (доп. опции)', default="Стандарт")
    client = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Клиент')
    service_company = models.ForeignKey(to='service.ServiceCompany', on_delete=models.CASCADE, verbose_name='Сервисная компания')

    def __str__(self):
        return f'{self.car_number}'

    class Meta:
        verbose_name = 'Машина'
        verbose_name_plural = 'Машины'

service/forms.py
from django import forms
from .models import *

class MaintenanceForm(forms.ModelForm):
    class Meta:
        model = Maintenance
        fields = '__all__'
        widgets ={
            'type': forms.RadioSelect()
        }

class ComplaintForm(forms.ModelForm):
    class Meta:
        model = Complaint
        fields = '__all__'

service/templates/service/complaint_car.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<a class="back-page" href="{% url 'car_list' %}"><i class="fas fa-long-arrow-alt-left"></i>Назад</a>
<div class="client">
    <i class="silant silant-vehicle"></i>
    <h2>Машина {{car.car_number}}</h2>
</div>
<nav class="nav-panel">
    <ul>
        <li><a href="{% url 'car_detail' car.pk %}"><i class="silant silant-service"></i> Сведения</a></li>
        <li><a href="{% url 'car_maintenance' car.pk %}"><i class="silant silant-maintenance"></i> ТО</a></li>
        <li class="active"><a href="{% url 'car_complaint' car.pk %}"><i class="silant silant-complaint"></i> Рекламации</a></li>
    </ul>
</nav>
<h3>Информация о комплектации и технических характеристиках Вашей техники</h3>
{% if user.is_superuser or user.groups.first.name == "Сервисная организация" or user.groups.first.name == "Менеджер" %}
<div class="action-buttons">
    <a href="{% url 'complaint_create' %}">Создать рекламацию</a>
</div>
{% endif %}
<section class="area-table"> 
<table id="tableComplaints" class="datatable" data-order='[0, "desc"]'>
    <thead class="datatable-thead">
        <tr>
            <th width="30%">Дата отказа</th>
            <th width="20%">Наработка, м/час</th>
            <th width="40%">Узел отказа</th>
            <th width="30%">Описание отказа</th>
            <th width="20%">Способ восстановления</th>
            <th width="20%">Используемые запасные части</th>
            <th width="30%">Дата восстановления</th>
            <th width="20%">Время простоя техники</th>
            <th width="30%">Сервисная компания</th>
            {% if user.is_superuser or user.groups.first.name == "Менеджер" or user.groups.first.name == "Сервисная организация" %}
            <th width="3%"></th>
            {% endif %}
        </tr>
    </thead>
    <tbody>
    {% for obj in object_list %}
        <tr>
            <td>{{obj.date_failure|date:"d.m.Y"}}</td>
            <td>{{obj.operating_time}}</td>
            <td><span class="description-js" data-url="{% url 'complaint_description' obj.pk 'node_failure' %}">{{obj.node_failure}}</span></td>
            <td>{{obj.description_failure}}</td>
            <td><span class="description-js" data-url="{% url 'complaint_description' obj.pk 'method_recovery' %}">{{obj.method_recovery}}</span></td>
            <td>{{obj.repair_parts}}</td>
            <td>{{obj.date_recovery|date:"d.m.Y"}}</td>
            <td>{{obj.downtime}}</td>
            {% if obj.service_company %}
            <td><span class="description-js" data-url="{% url 'complaint_description' obj.pk 'service_company' %}">{{obj.service_company}}</span></td>
            {% else %}
            <td>Нет компании</td>
            {% endif %}
            {% if user.is_superuser or user.groups.first.name == "Менеджер" or user.groups.first.name == "Сервисная организация" %}
            <td>
                <div class="actions">
                    <a class="update" href="{% url 'complaint_update' obj.pk %}"><i class="fas fa-pencil-alt"></i></a>
                    <a class="delete delete-js" data-url="{% url 'complaint_delete' obj.pk %}"><i class="fas fa-times"></i></a>
                </div>
            </td>
            {% endif %}
        </tr>
    {% endfor %}
    </tbody>
</table>
</section>
{% endblock %}

service/templates/service/complaint_confirm_delete.html
<a href="" class="modal-area"></a>
<form class="account-form modal-frame" method="post" action="{{request.path}}">
  {% csrf_token %}
    <span class="modal-exit"><i class="fas fa-times"></i></span>
    <div class="modal-body">
        <h1>Удаление</h1>
        {% if redirect_field_value %}
        <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
        {% endif %}
        <h4>Вы действительно хотите удалить {% if type == 'car' %}машину{% elif type == 'maintenance' %}ТО{% elif type == 'сomplaint' %}рекламацию{% endif %} {{object}}?</h4>
        <div class="modal-buttons">
            <button class="button" type="submit">Удалить</button>
            <span class="dummy-btn"></span>
            <button class="button button-alt cancel-js" type="reset">Отмена</button>
        </div>
    </div>
</form>

service/templates/service/complaint_create.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<a class="back-page" href="{% url 'complaint_list' %}"><i class="fas fa-long-arrow-alt-left"></i>Назад</a>
<h3>Создание рекламации</h3>
<form class="form" name="complaintForm" method="post" action="{{request.path}}">
    {% csrf_token %}
    <div><label for="id_date_failure">{{form.date_failure.label}}</label> {{form.date_failure}}</div>
    <div class="united">
        <label for="id_car">{{form.car.label}}</label> {{form.car}}
        <label for="id_operating_time">{{form.operating_time.label}}</label> {{form.operating_time}}
    </div>
    <div><label for="id_node_failure">{{form.node_failure.label}}</label> {{form.node_failure}}</div>
    <div><label for="id_description_failure">{{form.description_failure.label}}</label> {{form.description_failure}}</div>
    <div><label for="id_method_recovery">{{form.method_recovery.label}}</label> {{form.method_recovery}}</div>
    <div><label for="id_repair_parts">{{form.repair_parts.label}}</label> {{form.repair_parts}}</div>
    <div class="united">
        <label for="id_date_recovery">{{form.date_recovery.label}}</label> {{form.date_recovery}}
        <label for="id_downtime">{{form.downtime.label}}</label> {{form.downtime}}
    </div>
    <div><label for="id_service_company">{{form.service_company.label}}</label> {{form.service_company}}</div>
    <button type="submit">Сохранить</button>
</form>
{% endblock %}

service/templates/service/complaint_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="client">
    <i class="silant silant-client"></i>
    {% if user.is_superuser %}
        <h2>Администратор</h2>
    {% elif user.groups.first.name == "Менеджер" %}
        <h2>Менеджер {{user.first_name}}</h2>
    {% elif user.groups.first.name == "Сервисная организация" %}
        <h2>Сервисная организация {{user.userprofile.service_company}}</h2>
    {% else %}
        <h2>Клиент {{user.first_name}} </h2>
    {% endif %}
</div>
<nav class="nav-panel">
    <ul>
        <li><a href="{% url 'car_list' %}"><i class="silant silant-vehicle"></i> Машины</a></li>
        <li><a href="{% url 'maintenance_list' %}"><i class="silant silant-maintenance"></i> ТО</a></li>
        <li class="active"><a href="{% url 'complaint_list' %}"><i class="silant silant-complaint"></i> Рекламации</a></li>
    </ul>
</nav>
<h3>Информация о комплектации и технических характеристиках Вашей техники</h3>
{% if user.is_superuser or user.groups.first.name == "Сервисная организация" or user.groups.first.name == "Менеджер" %}
<div class="action-buttons">
    <a href="{% url 'complaint_create' %}">Создать рекламацию</a>
</div>
{% endif %}
<section class="area-table"> 
<table id="tableComplaints" class="datatable" data-order='[0, "desc"]'>
    <thead class="datatable-thead">
        <tr>
            <th width="30%">Дата отказа</th>
            <th width="20%">Наработка, м/час</th>
            <th width="40%">Узел отказа</th>
            <th width="30%">Описание отказа</th>
            <th width="20%">Способ восстановления</th>
            <th width="20%">Используемые запасные части</th>
            <th width="30%">Дата восстановления</th>
            <th width="20%">Время простоя техники</th>
            <th width="30%">Машина</th>
            <th width="30%">Сервисная компания</th>
            {% if user.is_superuser or user.groups.first.name == "Менеджер" or user.groups.first.name == "Сервисная организация" %}
            <th width="3%"></th>
            {% endif %}
        </tr>
    </thead>
    <tbody>
    {% for obj in object_list %}
        <tr>
            <td>{{obj.date_failure|date:"d.m.Y"}}</td>
            <td>{{obj.operating_time}}</td>
            <td><span class="description-js" data-url="{% url 'complaint_description' obj.pk 'node_failure' %}">{{obj.node_failure}}</span></td>
            <td>{{obj.description_failure}}</td>
            <td><span class="description-js" data-url="{% url 'complaint_description' obj.pk 'method_recovery' %}">{{obj.method_recovery}}</span></td>
            <td>{{obj.repair_parts}}</td>
            <td>{{obj.date_recovery|date:"d.m.Y"}}</td>
            <td>{{obj.downtime}}</td>
            <td><a href="{% url 'car_detail' obj.car.pk %}">{{obj.car}}</a></td>
            {% if obj.service_company %}
            <td><span class="description-js" data-url="{% url 'complaint_description' obj.pk 'service_company' %}">{{obj.service_company}}</span></td>
            {% else %}
            <td>Нет компании</td>
            {% endif %}
            {% if user.is_superuser or user.groups.first.name == "Менеджер" or user.groups.first.name == "Сервисная организация" %}
            <td>
                <div class="actions">
                    <a class="update" href="{% url 'complaint_update' obj.pk %}"><i class="fas fa-pencil-alt"></i></a>
                    <a class="delete delete-js" data-url="{% url 'complaint_delete' obj.pk %}"><i class="fas fa-times"></i></a>
                </div>
            </td>
            {% endif %}
        </tr>
    {% endfor %}
    </tbody>
</table>
</section>
{% endblock %}

service/templates/service/complaint_update.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<a class="back-page" href="{% url 'complaint_list' %}"><i class="fas fa-long-arrow-alt-left"></i>Назад</a>
<h3>Изменение рекламации</h3>
<form class="form" name="complaintForm" method="post" action="{{request.path}}">
    {% csrf_token %}
    <div><label for="id_date_failure">{{form.date_failure.label}}</label> {{form.date_failure}}</div>
    <div class="united">
        <label for="id_car">{{form.car.label}}</label> {{form.car}}
        <label for="id_operating_time">{{form.operating_time.label}}</label> {{form.operating_time}}
    </div>
    <div><label for="id_node_failure">{{form.node_failure.label}}</label> {{form.node_failure}}</div>
    <div><label for="id_description_failure">{{form.description_failure.label}}</label> {{form.description_failure}}</div>
    <div><label for="id_method_recovery">{{form.method_recovery.label}}</label> {{form.method_recovery}}</div>
    <div><label for="id_repair_parts">{{form.repair_parts.label}}</label> {{form.repair_parts}}</div>
    <div class="united">
        <label for="id_date_recovery">{{form.date_recovery.label}}</label> {{form.date_recovery}}
        <label for="id_downtime">{{form.downtime.label}}</label> {{form.downtime}}
    </div>
    <div><label for="id_service_company">{{form.service_company.label}}</label> {{form.service_company}}</div>
    <button type="submit">Сохранить</button>
</form>
{% endblock %}

service/templates/service/maintenance_car.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<a class="back-page" href="{% url 'car_list' %}"><i class="fas fa-long-arrow-alt-left"></i>Назад</a>
<div class="client">
    <i class="silant silant-vehicle"></i>
    <h2>Машина {{car.car_number}}</h2>
</div>
<nav class="nav-panel">
    <ul>
        <li><a href="{% url 'car_detail' car.pk %}"><i class="silant silant-service"></i> Сведения</a></li>
        <li class="active"><a href="{% url 'car_maintenance' car.pk %}"><i class="silant silant-maintenance"></i> ТО</a></li>
        <li><a href="{% url 'car_complaint' car.pk %}"><i class="silant silant-complaint"></i> Рекламации</a></li>
    </ul>
</nav>
<h3>Информация о комплектации и технических характеристиках Вашей техники</h3>
<div class="action-buttons">
    <a href="{% url 'maintenance_create' %}">Создать ТО</a>
</div>
<section class="area-table"> 
<table id="tableMaintenances" class="datatable" data-order='[0, "desc"]'>
    <thead class="datatable-thead">
        <tr>
            <th width="20%">Дата проведения ТО</th>
            <th width="30%">Вид ТО</th>
            <th width="20%">Наработка, м/час</th>
            <th width="20%">№ заказ-наряда</th>
            <th width="20%">Дата заказ-наряда</th>
            <th width="20%">Организация, проводившая ТО</th>
            <th width="3%"></th>
        </tr>
    </thead>
    <tbody>
    {% for obj in object_list %}
        <tr>
            <td>{{obj.date|date:"d.m.Y"}}</td>
            <td><span class="description-js" data-url="{% url 'maintenance_description' obj.pk 'type' %}">{{obj.type}}</span></td>
            <td>{{obj.operating_time}}</td>
            <td>{{obj.order_number}}</td>
            <td>{{obj.order_date|date:"d.m.Y"}}</td>
            {% if obj.service_company %}
            <td><span class="description-js" data-url="{% url 'maintenance_description' obj.pk 'service_company' %}">{{obj.service_company}}</span></td>
            {% else %}
            <td>Нет компании</td>
            {% endif %}
            <td>
                <div class="actions">
                    <a class="update" href="{% url 'maintenance_update' obj.pk %}"><i class="fas fa-pencil-alt"></i></a>
                    <a class="delete delete-js" data-url="{% url 'maintenance_delete' obj.pk %}"><i class="fas fa-times"></i></a>
                </div>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
</section>
{% endblock %}

service/templates/service/maintenance_confirm_delete.html
<a href="" class="modal-area"></a>
<form class="account-form modal-frame" method="post" action="{{request.path}}">
  {% csrf_token %}
    <span class="modal-exit"><i class="fas fa-times"></i></span>
    <div class="modal-body">
        <h1>Удаление</h1>
        {% if redirect_field_value %}
        <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
        {% endif %}
        <h4>Вы действительно хотите удалить {% if type == 'car' %}машину{% elif type == 'maintenance' %}ТО{% elif type == 'complaint' %}рекламацию{% endif %} {{object}}?</h4>
        <div class="modal-buttons">
            <button class="button" type="submit">Удалить</button>
            <span class="dummy-btn"></span>
            <button class="button button-alt cancel-js" type="reset">Отмена</button>
        </div>
    </div>
</form>

service/templates/service/maintenance_create.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<a class="back-page" href="{% url 'maintenance_list' %}"><i class="fas fa-long-arrow-alt-left"></i>Назад</a>
<h2>Создание ТО</h2>
<form class="form" name="maintenanceForm" method="post" action="{{request.path}}">
    {% csrf_token %}
    <div><label for="id_date">{{form.date.label}}</label> {{form.date}}</div>
    <div class="united">
        <label for="id_car">{{form.car.label}}</label> {{form.car}}
        <label for="id_operating_time">{{form.operating_time.label}}</label> {{form.operating_time}}
    </div>
    <div>{{form.type.label}}
        <div class="choices"> 
            {% for i, item in form.fields.type.widget.choices %}
            <div class="check-field">
                <input type="radio" name="type" value="{{i}}" id="id_type_{{i}}" {% for item in form.type.initial %}{% if i == item.pk %}checked=""{% endif %}{%endfor%}>
                <label for="id_type_{{i}}" class="check" name="active-check"><i class="fas fa-check"></i></label>
                <label for="id_type_{{i}}" class="check-text">{{item}}</label>
            </div>
            {% endfor %}
        </div> 
    </div>
    <div class="united">
        <label for="id_order_number">{{form.order_number.label}}</label> {{form.order_number}}
        <label for="id_order_date">{{form.order_date.label}}</label> {{form.order_date}}
    </div>
    <div><label for="id_service_company">{{form.service_company.label}}</label> {{form.service_company}}</div>
    <button type="submit">Сохранить</button>
</form>
{% endblock %}

service/templates/service/maintenance_update.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<a class="back-page" href="{% url 'maintenance_list' %}"><i class="fas fa-long-arrow-alt-left"></i>Назад</a>
<h3>Изменение ТО</h3>
<form class="form" name="maintenanceForm" method="post" action="{{request.path}}">
    {% csrf_token %}
    <div><label for="id_date">{{form.date.label}}</label> {{form.date}}</div>
    <div class="united">
        <label for="id_car">{{form.car.label}}</label> {{form.car}}
        <label for="id_operating_time">{{form.operating_time.label}}</label> {{form.operating_time}}
    </div>
    <div>{{form.type.label}}
        <div class="choices"> 
            {% for i, item in form.fields.type.widget.choices %}
            <div class="check-field">
                <input type="radio" name="type" value="{{i}}" id="id_type_{{i}}" {% if i == form.type.initial%}checked=""{% endif %}>
                <label for="id_type_{{i}}" class="check" name="active-check"><i class="fas fa-check"></i></label>
                <label for="id_type_{{i}}" class="check-text">{{item}}</label>
            </div>
            {% endfor %}
        </div> 
    </div>
    <div class="united">
        <label for="id_order_number">{{form.order_number.label}}</label> {{form.order_number}}
        <label for="id_order_date">{{form.order_date.label}}</label> {{form.order_date}}
    </div>
    <div><label for="id_service_company">{{form.service_company.label}}</label> {{form.service_company}}</div>
    <button type="submit">Сохранить</button>
</form>
{% endblock %}