silant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('service.urls')),
    path('', include('vehicles.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vehicles/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('search/', CarSearchView.as_view(), name='car_search_list'),
    path('cars/', CarListView.as_view(), name='car_list'),
    path('car/<pk>/detail', CarDetailView.as_view(), name='car_detail'),
    path('car/create', CarCreateView.as_view(), name='car_create'),
    path('car/<pk>/update', CarUpdateView.as_view(), name='car_update'),
    path('car/<pk>/delete', CarDeleteView.as_view(), name='car_delete'),
    path('car/<pk>/description/<atribute>', CarDescriptionView.as_view(), name='car_description'),

    path('api/cars/',CarListAPI.as_view(),name='car_list_api'),
    path('api/<user>/cars/',CarUserListAPI.as_view(),name='user_car_list_api'),
    path('api/car/<pk>/',CarDetailAPI.as_view(),name='car_detail_api'),
]

service/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
from vehicles.models import Car, UserProfile

class TypeMaintenance(models.Model):
    name = models.CharField(max_length=50, verbose_name='Название')
    description = models.TextField(verbose_name='Описание', blank=True, null=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Вид технического обслуживания'
        verbose_name_plural = 'Виды технических обслуживаний'

class Failure(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название')
    description = models.TextField(verbose_name='Описание', blank=True, null=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Характер отказа'
        verbose_name_plural = 'Характеры отказа'

class RecoveryMethod(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название')
    description = models.TextField(verbose_name='Описание', blank=True, null=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Способ восстановления'
        verbose_name_plural = 'Способы восстановления'

class ServiceCompany(models.Model):
    name = models.CharField(max_length=200, verbose_name='Название')
    description = models.TextField(verbose_name='Описание', blank=True, null=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Сервисная компания'
        verbose_name_plural = 'Сервисные компании'

class Maintenance(models.Model):
    type = models.ForeignKey(TypeMaintenance, on_delete=models.CASCADE, verbose_name='Вид ТО')
    date = models.DateField(default=datetime.now, verbose_name='Дата проведения ТО')
    operating_time = models.PositiveIntegerField(default=0, verbose_name='Наработка, м/час')
    order_number = models.CharField(max_length=20, verbose_name='№ заказ-наряда')
    order_date = models.DateField(default=datetime.now, verbose_name='Дата заказ-наряда')
    service_company = models.ForeignKey(ServiceCompany, on_delete=models.CASCADE, verbose_name='Организация, проводившая ТО', null=True, blank=True)
    car = models.ForeignKey(Car, on_delete=models.CASCADE, verbose_name='Машина')

    def __str__(self):
        return f'{self.date} {self.car}'

    class Meta:
        verbose_name = 'Техническое обслуживание'
        verbose_name_plural = 'Технические обслуживания'

class Complaint(models.Model):
    date_failure = models.DateField(default=datetime.now, verbose_name='Дата отказа')
    operating_time = models.PositiveIntegerField(default=0, verbose_name='Наработка, м/час')
    node_failure = models.ForeignKey(Failure, on_delete=models.CASCADE, verbose_name='Узел отказа')
    description_failure = models.TextField(blank=True, null=True, verbose_name='Описание отказа')
    method_recovery = models.ForeignKey(RecoveryMethod, on_delete=models.CASCADE, verbose_name='Способ восстановления')
    repair_parts = models.TextField(blank=True, null=True, verbose_name='Используемые запасные части')
    date_recovery = models.DateField(default=datetime.now, verbose_name='Дата восстановления')
    car = models.ForeignKey(Car, on_delete=models.CASCADE, verbose_name='Машина')
    service_company = models.ForeignKey(ServiceCompany, on_delete=models.CASCADE, verbose_name='Сервисная компания', null=True, blank=True)

    def __str__(self):
        return f'{self.date_failure} {self.car}'

    def downtime(self):
        deltatime = self.date_recovery - self.date_failure
        return deltatime.days

    class Meta:
        verbose_name = 'Рекламация'
        verbose_name_plural = 'Рекламации'

vehicles/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User 

class UserProfile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    is_service = models.BooleanField(default=False, blank=True, verbose_name='Является сотрудником сервисной компании')
    service_company = models.ForeignKey(to='service.ServiceCompany',blank=True, null=True, on_delete=models.PROTECT, verbose_name='Сервисная компания')

    def __str__(self):
        return f'{self.user.username} {self.is_service}'
    
    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'


class Technic(models.Model):
    name = models.CharField(max_length=20, verbose_name='Название')
    description = models.TextField(verbose_name='Описание', blank=True, null=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Модель техники'
        verbose_name_plural = 'Модели техники'

class Engine(models.Model):
    name = models.CharField(max_length=30, verbose_name='Название')
    description = models.TextField(verbose_name='Описание', blank=True, null=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Модель двигателя'
        verbose_name_plural = 'Модели двигателей'

class Transmission(models.Model):
    name = models.CharField(max_length=20, verbose_name='Название')
    description = models.TextField(verbose_name='Описание', blank=True, null=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Модель трансмиссии'
        verbose_name_plural = 'Модели трансмиссий'

class DrivingBridge(models.Model):
    name = models.CharField(max_length=20, verbose_name='Название')
    description = models.TextField(verbose_name='Описание', blank=True, null=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Модель ведущего моста'
        verbose_name_plural = 'Модели ведущих мостов'

class ControlledBridge(models.Model):
    name = models.CharField(max_length=20, verbose_name='Название')
    description = models.TextField(verbose_name='Описание', blank=True, null=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Модель управляемого моста'
        verbose_name_plural = 'Модели управляемых мостов'

class Car(models.Model):
    car_number = models.CharField(unique=True, max_length=12, verbose_name='Зав. № машины')
    technic = models.ForeignKey(Technic, on_delete=models.CASCADE, verbose_name='Модель техники')
    engine = models.ForeignKey(Engine, on_delete=models.CASCADE, verbose_name='Модель двигателя')
    engine_number = models.CharField(max_length=12, verbose_name='Зав. № двигателя')
    transmission = models.ForeignKey(Transmission, on_delete=models.CASCADE, verbose_name='Модель трансмиссии')
    transmission_number = models.CharField(max_length=12, verbose_name='Зав. № трансмиссии')
    driving_bridge = models.ForeignKey(DrivingBridge, on_delete=models.CASCADE, verbose_name='Модель ведущего моста')
    driving_bridge_number = models.CharField(max_length=12, verbose_name='Зав. № ведущего моста')
    controlled_bridge = models.ForeignKey(ControlledBridge, on_delete=models.CASCADE, verbose_name='Модель управляемого моста')
    controlled_bridge_number = models.CharField(max_length=12, verbose_name='Зав. № управляемого моста')
    delivery_contract = models.CharField(max_length=20, verbose_name='Договор поставки №, дата')
    date_shipment = models.DateField(default=datetime.now, verbose_name='Дата отгрузки с завода')
    consignee = models.CharField(max_length=200, verbose_name='Грузополучатель (конечный потребитель)')
    delivery_address = models.CharField(max_length=200, verbose_name='Адрес поставки (эксплуатации)')
    equipment = models.TextField(blank=False,verbose_name='Комплектация (доп. опции)', default="Стандарт")
    client = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Клиент')
    service_company = models.ForeignKey(to='service.ServiceCompany', on_delete=models.CASCADE, verbose_name='Сервисная компания')

    def __str__(self):
        return f'{self.car_number}'

    class Meta:
        verbose_name = 'Машина'
        verbose_name_plural = 'Машины'

vehicles/forms.py
from django import forms
from .models import *

class CarForm(forms.ModelForm):
    class Meta:
        model = Car
        fields = '__all__'

vehicles/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.db.models import Q
from vehicles.models import *
from service.models import *
from vehicles.forms import *
from vehicles.serializers import CarSerializer
from django.contrib.auth.mixins import PermissionRequiredMixin
from rest_framework import generics

# Главная
class HomeView(TemplateView):
    template_name = 'index.html'
    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('car_list')
        else:
            return redirect('car_search_list')

class CarSearchView(ListView):
    model = Car
    template_name = 'vehicles/car_search.html'
    queryset = Car.objects.all()

class CarListView(LoginRequiredMixin, ListView):
    model = Car
    template_name = 'vehicles/car_list.html'

    def get_queryset(self):
        if not self.request.user.is_staff:
            user = User.objects.get(pk = self.request.user.pk)
            try:
                profile = UserProfile.objects.get(user = user)
                if profile.is_service:
                    return Car.objects.filter(service_company = profile.service_company)
            except:
                return Car.objects.filter(client = user)
        else:
            return Car.objects.all()

class CarDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    permission_required = 'vehicles.view_car'
    model = Car
    template_name = 'vehicles/car_view.html'
    context_object_name = 'obj'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class CarCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = 'vehicles.add_car'
    model = Car
    form_class = CarForm
    template_name = 'vehicles/car_create.html'
    success_url = reverse_lazy('car_list')

class CarUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = 'vehicles.change_car'
    model = Car
    form_class = CarForm
    template_name = 'vehicles/car_update.html'
    success_url = reverse_lazy('car_list')

class CarDescriptionView(TemplateView):
    template_name= 'service/modal_description.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        car = Car.objects.get(pk = self.kwargs["pk"])
        atribute = context['atribute']
        if atribute == 'technic':
            context['atribute'] = car.technic
            context['description'] = car.technic.description 
        elif atribute == 'engine':
            context['atribute'] = car.engine
            context['description'] = car.engine.description 
        elif atribute == 'transmission':
            context['atribute'] = car.transmission
            context['description'] = car.transmission.description
        elif atribute == 'driving_bridge':
            context['atribute'] = car.driving_bridge
            context['description'] = car.driving_bridge.description 
        elif atribute == 'controlled_bridge':
            context['atribute'] = car.controlled_bridge
            context['description'] = car.controlled_bridge.description 
        elif atribute == 'equipment':
            context['atribute'] = 'Комплектация'
            context['description'] = car.equipment
        elif atribute == 'service_company':
            context['atribute'] = car.service_company
            context['description'] = car.service_company.description 
        return context

class CarDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    permission_required = 'vehicles.delete_car'
    model = Car
    template_name_suffix = '_confirm_delete'
    success_url = reverse_lazy('car_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["type"] = 'car'
        return context


# API
class CarListAPI(generics.ListAPIView):
    serializer_class = CarSerializer
    queryset = Car.objects.all()

class CarUserListAPI(generics.ListAPIView):
    serializer_class = CarSerializer
    
    def get_queryset(self):
        try:
            user = int(self.kwargs['user'])
        except:
            user = self.kwargs['user']
        if type(user) == int:
            queryset = Car.objects.filter(client = user)
        elif type(user) == str:
            queryset = Car.objects.filter(client__username = user)
        return queryset

class CarDetailAPI(generics.RetrieveAPIView):
    serializer_class = CarSerializer

    def get_object(self):
        obj = Car.objects.get(pk = self.kwargs['pk'])
        return obj

vehicles/templates/vehicles/car_confirm_delete.html
<a href="" class="modal-area"></a>
<form class="account-form modal-frame" method="post" action="{{request.path}}">
  {% csrf_token %}
    <span class="modal-exit"><i class="fas fa-times"></i></span>
    <div class="modal-body">
        <h1>Удаление</h1>
        {% if redirect_field_value %}
        <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
        {% endif %}
        <h4>Вы действительно хотите удалить {% if type == 'car' %}машину{% elif type == 'maintenance' %}ТО{% elif type == 'сomplaint' %}рекламацию{% endif %} {{object}}?</h4>
        <div class="modal-buttons">
            <button class="button" type="submit">Удалить</button>
            <span class="dummy-btn"></span>
            <button class="button button-alt cancel-js" type="reset">Отмена</button>
        </div>
    </div>
</form>

vehicles/templates/vehicles/car_create.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<a class="back-page" href="{% url 'car_list' %}"><i class="fas fa-long-arrow-alt-left"></i>Назад</a>
<h3>Создание машины</h3>
<form class="form" name="carForm" method="post" action="{{request.path}}">
    {% csrf_token %}
    <div class="united">
        <label for="id_car_number">{{form.car_number.label}}</label> {{form.car_number}}
        <label for="id_technic">{{form.technic.label}}</label> {{form.technic}}
    </div>
    <div class="united">
        <label for="id_engine">{{form.engine.label}}</label> {{form.engine}}
        <label for="id_engine_number">{{form.engine_number.label}}</label> {{form.engine_number}}
    </div>
    <div class="united">
        <label for="id_transmission">{{form.transmission.label}}</label> {{form.transmission}}
        <label for="id_transmission_number">{{form.transmission_number.label}}</label> {{form.transmission_number}}
    </div>
    <div class="united">
        <label for="id_driving_bridge">{{form.driving_bridge.label}}</label> {{form.driving_bridge}}
        <label for="id_driving_bridge_number">{{form.driving_bridge_number.label}}</label> {{form.driving_bridge_number}}
    </div>
    <div class="united">
        <label for="id_controlled_bridge">{{form.controlled_bridge.label}}</label> {{form.controlled_bridge}}
        <label for="id_controlled_bridge_number">{{form.controlled_bridge_number.label}}</label> {{form.controlled_bridge_number}}
    </div>
    <div class="united">
        <label for="id_delivery_contract">{{form.delivery_contract.label}}</label> {{form.delivery_contract}}
        <label for="id_date_shipment">{{form.date_shipment.label}}</label> {{form.date_shipment}}
    </div>
    <div><label for="id_consignee">{{form.consignee.label}}</label> {{form.consignee}}</div>
    <div><label for="id_delivery_address">{{form.delivery_address.label}}</label> {{form.delivery_address}}</div>
    <div><label for="id_equipment">{{form.equipment.label}}</label> {{form.equipment}}</div>
    <div class="united">
        <label for="id_client">{{form.client.label}}</label> {{form.client}}
        <label for="id_service_company">{{form.service_company.label}}</label> {{form.service_company}}
    </div>
    <button type="submit">Сохранить</button>
</form>
{% endblock %}

vehicles/templates/vehicles/car_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="client">
<i class="silant silant-client"></i>
{% if user.is_superuser %}
    <h2>Администратор</h2>
{% elif user.groups.first.name == "Менеджер" %}
    <h2>Менеджер {{user.first_name}}</h2>
{% elif user.groups.first.name == "Сервисная организация" %}
    <h2>Сервисная организация {{user.userprofile.service_company}}</h2>
{% else %}
    <h2>Клиент {{user.first_name}} </h2>
{% endif %}
</div>
<nav class="nav-panel">
    <ul>
        <li class="active"><a href="{% url 'car_list' %}"><i class="silant silant-vehicle"></i> Машины</a></li>
        <li><a href="{% url 'maintenance_list' %}"><i class="silant silant-maintenance"></i> ТО</a></li>
        <li><a href="{% url 'complaint_list' %}"><i class="silant silant-complaint"></i> Рекламации</a></li>
    </ul>
</nav>
<h3>Информация о комплектации и технических характеристиках Вашей техники</h3>
{% if user.is_superuser or user.groups.first.name == "Менеджер" %}
<div class="action-buttons">
    <a href="{% url 'car_create' %}">Добавить машину</a>
</div>
{% endif %}
<section class="area-table"> 
    <table id="tableCars" class="datatable" data-order='[0, "asc"]'>
        <thead class="datatable-thead">
            <tr>
                <th>Зав. № машины</th>
                <th>Модель техники</th>
                <th>Модель двигателя</th>
                <th>Зав. № двигателя</th>
                <th>Модель трансмиссии</th>
                <th>Зав. № трансмиссии</th>
                <th>Модель ведущего моста</th>
                <th>Зав. № ведущего моста</th>
                <th>Модель управляемого моста</th>
                <th>Зав. № управляемого моста</th>
                <th>Договор поставки №, дата</th>
                <th>Дата отгрузки с завода</th>
                <th>Грузополучатель (конечный потребитель)</th>
                <th>Адрес поставки (эксплуатации)</th>
                <th>Комплектация (доп. опции)</th>
                <th>Клиент</th>
                <th>Сервисная компания</th>
                {% if user.is_superuser or user.groups.first.name == "Менеджер" %}
                <th width="3%"></th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
        {% for obj in object_list %}
            <tr>
                <td><a href="{% url 'car_detail' obj.pk %}">{{obj.car_number}}</a></td>
                <td><span class="description-js" data-url="{% url 'car_description' obj.pk 'technic' %}">{{obj.technic}}</span></td>
                <td><span class="description-js" data-url="{% url 'car_description' obj.pk 'engine' %}">{{obj.engine}}</span></td>
                <td>{{obj.engine_number}}</td>
                <td><span class="description-js" data-url="{% url 'car_description' obj.pk 'transmission' %}">{{obj.transmission}}</span></td>
                <td>{{obj.transmission_number}}</td>
                <td><span class="description-js" data-url="{% url 'car_description' obj.pk 'driving_bridge' %}">{{obj.driving_bridge}}</span></td>
                <td>{{obj.driving_bridge_number}}</td>
                <td><span class="description-js" data-url="{% url 'car_description' obj.pk 'controlled_bridge' %}">{{obj.controlled_bridge}}</span></td>
                <td>{{obj.controlled_bridge_number}}</td>
                <td>{{obj.delivery_contract}}</td>
                <td>{{obj.date_shipment|date:"d.m.Y"}}</td>
                <td>{{obj.consignee}}</td>
                <td>{{obj.delivery_address}}</td>
                {% if obj.equipment == 'Стандарт'%}
                <td>{{obj.equipment}}</td>
                {% else %}
                <td><span class="description-js" data-url="{% url 'car_description' obj.pk 'equipment' %}">Посмотреть</span></td>
                {% endif %}
                <td>{{obj.client}}</td>
                {% if obj.service_company %}
                    <td><span class="description-js" data-url="{% url 'maintenance_description' obj.pk 'service_company' %}">{{obj.service_company}}</span></td>
                {% else %}
                    <td>Нет компании</td>
                {% endif %}
                {% if user.is_superuser or user.groups.first.name == "Менеджер" %}
                <td>
                    <div class="actions">
                        <a class="update" href="{% url 'car_update' obj.pk %}"><i class="fas fa-pencil-alt"></i></a>
                        <a class="delete delete-js" data-url="{% url 'car_delete' obj.pk %}"><i class="fas fa-times"></i></a>
                    </div>
                </td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
</section>
{% endblock %}

vehicles/templates/vehicles/car_search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h4>Проверьте комплектацию и технические характеристики техники Силант</h4>
<form id="search" class="search" method="get">
    <input id="search-input" type="search" name="q" placeholder="Введите заводской номер машины">
    <button id="search-button" type="button">Найти</button>
</form>
<h3>Информация о комплектации и технических характеристиках Вашей техники</h3>
<section class="area-table"> 
    <table id="tableCars" class="datatable" data-order='[0, "asc"]'>
        <thead class="datatable-thead">
            <tr>
                <th>Зав. № машины</th>
                <th>Модель техники</th>
                <th>Модель двигателя</th>
                <th>Зав. № двигателя</th>
                <th>Модель трансмиссии</th>
                <th>Зав. № трансмиссии</th>
                <th>Модель ведущего моста</th>
                <th>Зав. № ведущего моста</th>
                <th>Модель управляемого моста</th>
                <th>Зав. № управляемого моста</th>
            </tr>
        </thead>
        <tbody>
        {% for obj in object_list %}
            <tr>
                <td>{{obj.car_number}}</td>
                <td><span class="description-js" data-url="{% url 'car_description' obj.pk 'technic' %}">{{obj.technic}}</span></td>
                <td><span class="description-js" data-url="{% url 'car_description' obj.pk 'engine' %}">{{obj.engine}}</span></td>
                <td>{{obj.engine_number}}</td>
                <td><span class="description-js" data-url="{% url 'car_description' obj.pk 'transmission' %}">{{obj.transmission}}</span></td>
                <td>{{obj.transmission_number}}</td>
                <td><span class="description-js" data-url="{% url 'car_description' obj.pk 'driving_bridge' %}">{{obj.driving_bridge}}</span></td>
                <td>{{obj.driving_bridge_number}}</td>
                <td><span class="description-js" data-url="{% url 'car_description' obj.pk 'controlled_bridge' %}">{{obj.controlled_bridge}}</span></td>
                <td>{{obj.controlled_bridge_number}}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</section>
{% endblock %}

vehicles/templates/vehicles/car_update.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<a class="back-page" href="{% url 'car_list' %}"><i class="fas fa-long-arrow-alt-left"></i>Назад</a>
<h3>Изменение машины</h3>
<form class="form" name="carForm" method="post" action="{{request.path}}">
    {% csrf_token %}
    <div class="united">
        <label for="id_car_number">{{form.car_number.label}}</label> {{form.car_number}}
        <label for="id_technic">{{form.technic.label}}</label> {{form.technic}}
    </div>
    <div class="united">
        <label for="id_engine">{{form.engine.label}}</label> {{form.engine}}
        <label for="id_engine_number">{{form.engine_number.label}}</label> {{form.engine_number}}
    </div>
    <div class="united">
        <label for="id_transmission">{{form.transmission.label}}</label> {{form.transmission}}
        <label for="id_transmission_number">{{form.transmission_number.label}}</label> {{form.transmission_number}}
    </div>
    <div class="united">
        <label for="id_driving_bridge">{{form.driving_bridge.label}}</label> {{form.driving_bridge}}
        <label for="id_driving_bridge_number">{{form.driving_bridge_number.label}}</label> {{form.driving_bridge_number}}
    </div>
    <div class="united">
        <label for="id_controlled_bridge">{{form.controlled_bridge.label}}</label> {{form.controlled_bridge}}
        <label for="id_controlled_bridge_number">{{form.controlled_bridge_number.label}}</label> {{form.controlled_bridge_number}}
    </div>
    <div class="united">
        <label for="id_delivery_contract">{{form.delivery_contract.label}}</label> {{form.delivery_contract}}
        <label for="id_date_shipment">{{form.date_shipment.label}}</label> {{form.date_shipment}}
    </div>
    <div><label for="id_consignee">{{form.consignee.label}}</label> {{form.consignee}}</div>
    <div><label for="id_delivery_address">{{form.delivery_address.label}}</label> {{form.delivery_address}}</div>
    <div><label for="id_equipment">{{form.equipment.label}}</label> {{form.equipment}}</div>
    <div class="united">
        <label for="id_client">{{form.client.label}}</label> {{form.client}}
        <label for="id_service_company">{{form.service_company.label}}</label> {{form.service_company}}
    </div>
    <button type="submit">Сохранить</button>
</form>
{% endblock %}